# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-16 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20161016_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='feeling',
            new_name='tips_type',
        ),
    ]
